"use strict";
let paqueteActual=null,cantidad=1,opinionesActuales=[];
const $=id=>document.getElementById(id);
const money=v=>new Intl.NumberFormat("es-PE",{style:"currency",currency:"PEN"}).format(Number(v)||0);
const imgUrl=imagen=>{if(!imagen)return "https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=1400&q=85";const x=String(imagen).trim();if(/^https?:\/\//i.test(x)||x.startsWith("data:"))return x;if(x.startsWith("/"))return `${API_CONFIG.backendUrl}${x}`;return `${API_CONFIG.backendUrl}/${x}`};
function arreglarLinksCabecera(){document.querySelectorAll('#navigation a[href^="#"]').forEach(a=>a.href=`./index.html${a.getAttribute("href")}`)}
function toast(t){const d=document.createElement("div");d.className="detail-toast";d.textContent=t;$('toastContainer').appendChild(d);setTimeout(()=>d.remove(),3000)}
function actualizarTotal(){if(!paqueteActual)return;$('cantidadPersonas').textContent=cantidad;$('precioTotal').textContent=money(paqueteActual.precio*cantidad)}
async function cargarOpiniones(id){try{const r=await fetch(`${API_CONFIG.baseUrl}${API_CONFIG.endpoints.opiniones}/paquete/${id}`);if(!r.ok)return;opinionesActuales=await r.json();const n=opinionesActuales.length;$('cantidadOpiniones').textContent=`${n} ${n===1?'opinión':'opiniones'}`;if(n){const avg=opinionesActuales.reduce((a,o)=>a+Number(o.calificacion||0),0)/n;$('resumenRating').innerHTML=`<strong>★ ${avg.toFixed(1)}</strong><span>${n} ${n===1?'opinión':'opiniones'}</span>`;$('listaOpiniones').innerHTML=opinionesActuales.map(o=>`<article class="review-item"><div class="review-top"><strong>${esc(o.usuario||'Viajero')}</strong><span class="review-stars">${'★'.repeat(Math.max(1,Math.min(5,Number(o.calificacion)||1)))}</span></div><p>${esc(o.comentario||'Excelente experiencia.')}</p></article>`).join('')}else $('listaOpiniones').innerHTML='<p>Aún no hay opiniones para este paquete. ¡Sé el primero en vivir la experiencia!</p>'}catch(e){console.warn(e)}}
function esc(v){const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML}
async function cargar(){arreglarLinksCabecera();setTimeout(arreglarLinksCabecera,150);const id=Number(new URLSearchParams(location.search).get('id'));if(!Number.isInteger(id)||id<=0)return error('No se pudo identificar el paquete seleccionado.');try{const r=await fetch(`${API_CONFIG.baseUrl}${API_CONFIG.endpoints.paquetes}/${id}`);if(!r.ok)throw new Error('Paquete no encontrado');paqueteActual=await r.json();pintar(paqueteActual);await cargarOpiniones(id);$('detalleCarga').hidden=true;$('detalleContenido').hidden=false}catch(e){error('No se pudo cargar este paquete. Verifica que el backend esté ejecutándose e inténtalo nuevamente.')}}
function lineas(v){return String(v||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}
function pintarLista(id,v,icon='fa-check'){const el=$(id);if(!el)return;const xs=lineas(v);el.innerHTML=xs.length?xs.map(x=>`<div class="detail-list-item"><i class="fa-solid ${icon}"></i><span>${esc(x)}</span></div>`).join(''):'<p>Información por confirmar con Ligor Travel.</p>'}
function pintarItinerario(v){const el=$('detalleItinerario');const xs=lineas(v);el.innerHTML=xs.length?xs.map((x,i)=>`<div class="itinerary-item"><span>${i+1}</span><p>${esc(x)}</p></div>`).join(''):'<p>El itinerario será confirmado al realizar la reserva.</p>'}
function pintarHorarios(v){const sel=$('horarioReservaDetalle'),xs=String(v||'').split(/[,;\n]/).map(x=>x.trim()).filter(Boolean);$('bloqueHorario').hidden=!xs.length;sel.innerHTML=xs.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}
function pintar(p){document.title=`${p.nombre} | Ligor Travel`;$('migaNombre').textContent=p.nombre;$('detalleNombre').textContent=p.nombre;$('detalleDestino').textContent=p.destino||'Perú';$('detalleDestinoInfo').textContent=p.destino||'Perú';$('detalleCategoria').textContent=p.categoria||'Experiencia';$('detalleCategoriaInfo').textContent=p.categoria||'Experiencia';$('detalleDescripcion').textContent=p.descripcion||'Descubre una experiencia turística inolvidable con Ligor Travel.';const dias=Number(p.duracionDias)||1;$('detalleDuracion').textContent=`${dias} ${dias===1?'día':'días'}`;const cupos=Math.max(0,Number(p.cupos)||0);$('detalleCupos').textContent=`${cupos} ${cupos===1?'cupo':'cupos'}`;$('detalleImagen').src=imgUrl(p.imagen);$('detalleImagen').alt=p.nombre;$('detallePrecio').textContent=money(p.precio);$('precioPersona').textContent=money(p.precio);pintarLista('detalleQueViviras',p.queViviras,'fa-check');pintarItinerario(p.itinerario);pintarLista('detalleIncluye',p.incluye,'fa-check');pintarLista('detalleNoIncluye',p.noIncluye,'fa-xmark');pintarLista('detalleRecomendaciones',p.recomendaciones,'fa-circle-info');pintarHorarios(p.horarios);$('bloqueRecojo').hidden=!p.puntoRecojo;$('detallePuntoRecojo').textContent=p.puntoRecojo||'';const hoy=new Date();hoy.setMinutes(hoy.getMinutes()-hoy.getTimezoneOffset());$('fechaReservaDetalle').min=hoy.toISOString().slice(0,10);actualizarTotal()}
function error(t){$('detalleCarga').hidden=true;$('detalleError').hidden=false;$('detalleError').textContent=t}
function reservar(){if(!paqueteActual)return;const fecha=$('fechaReservaDetalle').value;if(!fecha){toast('Selecciona una fecha para continuar.');return}const sesion=(typeof obtenerAlmacenamientoSesion==='function')?obtenerAlmacenamientoSesion():null;if(!sesion){toast('Inicia sesión para reservar este paquete.');$('btnLogin')?.click();return}sessionStorage.setItem('ligor_paquete_seleccionado',String(paqueteActual.id));sessionStorage.setItem('ligor_reserva_fecha',fecha);sessionStorage.setItem('ligor_reserva_personas',String(cantidad));const horario=$('horarioReservaDetalle')?.value||'';if(horario)sessionStorage.setItem('ligor_reserva_horario',horario);toast(`Paquete seleccionado para ${cantidad} ${cantidad===1?'persona':'personas'}.`);setTimeout(()=>location.href='./mi-cuenta.html',700)}
document.addEventListener('DOMContentLoaded',()=>{$('restarPersona').addEventListener('click',()=>{cantidad=Math.max(1,cantidad-1);actualizarTotal()});$('sumarPersona').addEventListener('click',()=>{const max=Math.max(1,Number(paqueteActual?.cupos)||1);cantidad=Math.min(max,cantidad+1);actualizarTotal()});$('btnReservarDetalle').addEventListener('click',reservar);cargar()});
