"use strict";
let configuracionActual=null, seleccionado=null, elementos=[], fondoX=50, fondoY=50;
document.addEventListener("DOMContentLoaded",async()=>{if(!proteger())return; eventos(); await cargar();});
function proteger(){const u=obtenerUsuarioSesion(),t=obtenerTokenSesion();if(!u||!t||String(u.rol||"").toLowerCase()!=="administrador"){location.href="../index.html";return false}return true}
function url(){return obtenerUrlApi(API_CONFIG.endpoints.configuracionSitio)}
function imgUrl(r){if(!r)return "";if(/^https?:/i.test(r))return r;return `${API_CONFIG.baseUrl.replace(/\/api\/?$/i,"")}${r.startsWith("/")?r:"/"+r}`}
function eventos(){
 document.getElementById("heroImagenAdmin").addEventListener("change",e=>{const f=e.target.files[0];if(f)document.getElementById("editorStage").style.backgroundImage=`url('${URL.createObjectURL(f)}')`});
 document.getElementById("btnSubirImagen").onclick=subirImagen; document.getElementById("btnAgregarTexto").onclick=agregarTexto; document.getElementById("btnEliminarTexto").onclick=()=>{if(seleccionado){seleccionado.remove();elementos=elementos.filter(x=>x.el!==seleccionado);seleccionado=null}};
 document.getElementById("colorTexto").oninput=e=>aplicar("color",e.target.value); document.getElementById("fuenteTexto").onchange=e=>aplicar("fontFamily",e.target.value); document.getElementById("tamanoTexto").oninput=e=>aplicar("fontSize",e.target.value+"px");
 document.getElementById("btnNegrita").onclick=()=>{if(seleccionado)seleccionado.style.fontWeight=seleccionado.style.fontWeight==="700"?"400":"700"}; document.getElementById("btnCursiva").onclick=()=>{if(seleccionado)seleccionado.style.fontStyle=seleccionado.style.fontStyle==="italic"?"normal":"italic"};
 document.getElementById("btnGuardarDiseno").onclick=guardar;
 const stage=document.getElementById("editorStage");
 stage.addEventListener("dblclick",e=>{if(!e.target.closest(".editor-text"))abrirPosicionImagen()});
 document.querySelectorAll("#positionGrid button").forEach(b=>b.onclick=()=>posicionarImagen(+b.dataset.x,+b.dataset.y));
 document.getElementById("btnCentrarImagen").onclick=()=>posicionarImagen(50,50);
 document.getElementById("btnCerrarPosicion").onclick=cerrarPosicionImagen;
 document.getElementById("modalPosicionImagen").addEventListener("click",e=>{if(e.target.id==="modalPosicionImagen")cerrarPosicionImagen()});
}
function aplicar(p,v){if(seleccionado)seleccionado.style[p]=v}
function aplicarPosicionFondo(){document.getElementById("editorStage").style.backgroundPosition=`${fondoX}% ${fondoY}%`;document.querySelectorAll("#positionGrid button").forEach(b=>b.classList.toggle("active",+b.dataset.x===fondoX&&+b.dataset.y===fondoY))}
function abrirPosicionImagen(){const stage=document.getElementById("editorStage");if(!stage.style.backgroundImage)return mensaje("Primero selecciona o aplica una imagen.","error");aplicarPosicionFondo();const m=document.getElementById("modalPosicionImagen");m.classList.add("open");m.setAttribute("aria-hidden","false")}
function cerrarPosicionImagen(){const m=document.getElementById("modalPosicionImagen");m.classList.remove("open");m.setAttribute("aria-hidden","true")}
function posicionarImagen(x,y){fondoX=x;fondoY=y;aplicarPosicionFondo();mensaje("Posición ajustada. Pulsa Guardar diseño para conservarla.","success")}
async function cargar(){try{const r=await fetch(url(),{cache:"no-store"}),c=await r.json();configuracionActual=c; if(c.heroImagen){document.getElementById("editorStage").style.backgroundImage=`url('${imgUrl(c.heroImagen)}')`;document.getElementById("editorHint").style.display="none"} if(c.heroDisenoJson){const d=JSON.parse(c.heroDisenoJson);fondoX=Number.isFinite(+d.fondoX)?+d.fondoX:50;fondoY=Number.isFinite(+d.fondoY)?+d.fondoY:50;aplicarPosicionFondo();(d.textos||[]).forEach(crearDesdeDatos)}}catch(e){mensaje("No se pudo cargar el diseño: "+e.message,"error")}}
function agregarTexto(){const texto=prompt("Escribe el texto que deseas agregar:","Nuevo texto");if(!texto)return;crearDesdeDatos({texto,x:12,y:25,color:document.getElementById("colorTexto").value,fuente:document.getElementById("fuenteTexto").value,tamano:+document.getElementById("tamanoTexto").value,negrita:true,cursiva:false})}
function crearDesdeDatos(d){const s=document.getElementById("editorStage"),el=document.createElement("div");el.className="editor-text";el.textContent=d.texto||"Texto";Object.assign(el.style,{left:(d.x??10)+"%",top:(d.y??20)+"%",color:d.color||"#fff",fontFamily:d.fuente||"Arial",fontSize:(d.tamano||42)+"px",fontWeight:d.negrita?"700":"400",fontStyle:d.cursiva?"italic":"normal"});s.appendChild(el);elementos.push({el});el.onclick=e=>{e.stopPropagation();seleccionar(el)};el.ondblclick=()=>{const t=prompt("Editar texto:",el.textContent);if(t!==null)el.textContent=t};hacerArrastrable(el);seleccionar(el)}
function seleccionar(el){document.querySelectorAll(".editor-text").forEach(x=>x.classList.remove("selected"));seleccionado=el;el.classList.add("selected");document.getElementById("colorTexto").value=rgbHex(getComputedStyle(el).color);document.getElementById("fuenteTexto").value=el.style.fontFamily;document.getElementById("tamanoTexto").value=parseInt(el.style.fontSize)||42}
function hacerArrastrable(el){let sx,sy,l,t,m=false;el.addEventListener("pointerdown",e=>{m=true;sx=e.clientX;sy=e.clientY;l=el.offsetLeft;t=el.offsetTop;el.setPointerCapture(e.pointerId)});el.addEventListener("pointermove",e=>{if(!m)return;const s=document.getElementById("editorStage");let nx=Math.max(0,Math.min(s.clientWidth-el.offsetWidth,l+e.clientX-sx)),ny=Math.max(0,Math.min(s.clientHeight-el.offsetHeight,t+e.clientY-sy));el.style.left=nx/s.clientWidth*100+"%";el.style.top=ny/s.clientHeight*100+"%"});el.addEventListener("pointerup",()=>m=false)}
async function subirImagen(){const f=document.getElementById("heroImagenAdmin").files[0];if(!f)return mensaje("Selecciona una imagen primero.","error");const fd=new FormData();fd.append("archivo",f);try{mensaje("Subiendo imagen...");const r=await fetch(url()+"/subir-hero",{method:"POST",headers:{Authorization:`Bearer ${obtenerTokenSesion()}`},body:fd});const j=await r.json();if(!r.ok)throw new Error(j.mensaje||"Error al subir");configuracionActual={...(configuracionActual||{}),...(j.configuracion||{}),heroImagen:j.imagen};document.getElementById("editorStage").style.backgroundImage=`url('${imgUrl(j.imagen)}')`;document.getElementById("editorHint").style.display="none";mensaje("Imagen aplicada correctamente.","success")}catch(e){mensaje(e.message,"error")}}
async function guardar(){if(!configuracionActual)return;const s=document.getElementById("editorStage");const textos=elementos.map(({el})=>({texto:el.textContent,x:parseFloat(el.style.left)||0,y:parseFloat(el.style.top)||0,color:rgbHex(getComputedStyle(el).color),fuente:el.style.fontFamily||"Arial",tamano:parseInt(el.style.fontSize)||42,negrita:el.style.fontWeight==="700",cursiva:el.style.fontStyle==="italic"}));const body={...configuracionActual,heroDisenoJson:JSON.stringify({version:2,fondoX,fondoY,textos})};try{mensaje("Guardando diseño...");const r=await fetch(url(),{method:"PUT",headers:{"Content-Type":"application/json",Authorization:`Bearer ${obtenerTokenSesion()}`},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.mensaje||"No se pudo guardar");configuracionActual=j.configuracion||body;mensaje("Diseño guardado. Ya se verá en la página principal.","success")}catch(e){mensaje(e.message,"error")}}
function mensaje(t,c=""){const e=document.getElementById("mensajeEditor");e.textContent=t;e.className="editor-message "+c}
function rgbHex(c){if(c.startsWith("#"))return c;const m=c.match(/\d+/g);return m?"#"+m.slice(0,3).map(x=>(+x).toString(16).padStart(2,"0")).join(""):"#ffffff"}
