// <auto-generated />
using System;
using LigorTravel.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LigorTravel.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LigorTravel.API.Models.ConfiguracionSitio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Facebook")
                        .HasColumnType("text");

                    b.Property<bool>("HeroActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("HeroBotonIA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeroBotonPrincipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeroDescripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeroDisenoJson")
                        .HasColumnType("text");

                    b.Property<string>("HeroEtiqueta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeroImagen")
                        .HasColumnType("text");

                    b.Property<string>("HeroSubtitulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeroTitulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instagram")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<string>("TikTok")
                        .HasColumnType("text");

                    b.Property<string>("Whatsapp")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionesSitio");
                });

            modelBuilder.Entity("LigorTravel.API.Models.Mensaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("LigorTravel.API.Models.Opinion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Calificacion")
                        .HasColumnType("integer");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaqueteId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PaqueteId");

                    b.HasIndex("UsuarioId", "PaqueteId")
                        .IsUnique();

                    b.ToTable("Opiniones", t =>
                        {
                            t.HasCheckConstraint("CK_Opiniones_Calificacion", "\"Calificacion\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("LigorTravel.API.Models.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("ReservaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReservaId")
                        .IsUnique();

                    b.ToTable("Pagos", t =>
                        {
                            t.HasCheckConstraint("CK_Pagos_Monto", "\"Monto\" >= 0");
                        });
                });

            modelBuilder.Entity("LigorTravel.API.Models.Paquete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Cupos")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DuracionDias")
                        .HasColumnType("integer");

                    b.Property<string>("Imagen")
                        .HasColumnType("text");

                    b.Property<string>("Horarios")
                        .HasColumnType("text");

                    b.Property<string>("PuntoRecojo")
                        .HasColumnType("text");

                    b.Property<string>("QueViviras")
                        .HasColumnType("text");

                    b.Property<string>("Itinerario")
                        .HasColumnType("text");

                    b.Property<string>("Incluye")
                        .HasColumnType("text");

                    b.Property<string>("NoIncluye")
                        .HasColumnType("text");

                    b.Property<string>("Recomendaciones")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.ToTable("Paquetes", t =>
                        {
                            t.HasCheckConstraint("CK_Paquetes_Cupos", "\"Cupos\" >= 0");

                            t.HasCheckConstraint("CK_Paquetes_Duracion", "\"DuracionDias\" > 0");

                            t.HasCheckConstraint("CK_Paquetes_Precio", "\"Precio\" >= 0");
                        });
                });

            modelBuilder.Entity("LigorTravel.API.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadPersonas")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PaqueteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PaqueteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Reservas", t =>
                        {
                            t.HasCheckConstraint("CK_Reservas_Cantidad", "\"CantidadPersonas\" > 0");

                            t.HasCheckConstraint("CK_Reservas_Total", "\"Total\" >= 0");
                        });
                });

            modelBuilder.Entity("LigorTravel.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios", t =>
                        {
                            t.HasCheckConstraint("CK_Usuarios_Rol", "\"Rol\" IN ('Cliente','Vendedor','Administrador')");
                        });
                });

            modelBuilder.Entity("LigorTravel.API.Models.Mensaje", b =>
                {
                    b.HasOne("LigorTravel.API.Models.Usuario", "Usuario")
                        .WithMany("Mensajes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LigorTravel.API.Models.Opinion", b =>
                {
                    b.HasOne("LigorTravel.API.Models.Paquete", "Paquete")
                        .WithMany("Opiniones")
                        .HasForeignKey("PaqueteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LigorTravel.API.Models.Usuario", "Usuario")
                        .WithMany("Opiniones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paquete");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LigorTravel.API.Models.Pago", b =>
                {
                    b.HasOne("LigorTravel.API.Models.Reserva", "Reserva")
                        .WithOne("Pago")
                        .HasForeignKey("LigorTravel.API.Models.Pago", "ReservaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("LigorTravel.API.Models.Reserva", b =>
                {
                    b.HasOne("LigorTravel.API.Models.Paquete", "Paquete")
                        .WithMany("Reservas")
                        .HasForeignKey("PaqueteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LigorTravel.API.Models.Usuario", "Usuario")
                        .WithMany("Reservas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paquete");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("LigorTravel.API.Models.Paquete", b =>
                {
                    b.Navigation("Opiniones");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("LigorTravel.API.Models.Reserva", b =>
                {
                    b.Navigation("Pago");
                });

            modelBuilder.Entity("LigorTravel.API.Models.Usuario", b =>
                {
                    b.Navigation("Mensajes");

                    b.Navigation("Opiniones");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
